/*!
 * sync-env.js
 *
 * Prisma reads `.env` from the schema's directory (packages/db/),
 * while NestJS reads it from the repo root via envFilePath. To keep
 * a single source of truth, this script mirrors the root `.env` into
 * `packages/db/.env` before every Prisma invocation.
 *
 * Invoked automatically by the `prisma:*` and `seed` npm scripts
 * declared in this package.json, so users can edit one file and have
 * every tool — Nest, Prisma CLI, prisma migrate, prisma studio —
 * see the same values.
 *
 * CI / build-only contexts (GitHub Actions VPS deploy workflow,
 * Coolify image builds) don't have a real `.env` — they only run
 * `prisma generate` to emit the typed client, never connecting to a
 * DB. For those, fall back to writing a placeholder DATABASE_URL so
 * Prisma CLI can parse the schema without complaining. Any actual
 * `prisma migrate` / `prisma db push` run must still have a real
 * DATABASE_URL — that path is unaffected.
 */
const fs = require("fs");
const path = require("path");

const ROOT_ENV = path.resolve(__dirname, "..", "..", "..", ".env");
const LOCAL_ENV = path.resolve(__dirname, "..", ".env");

const keysToMirror = ["DATABASE_URL", "SMTP_ENCRYPTION_KEY"];

if (!fs.existsSync(ROOT_ENV)) {
  // Build-only context: write placeholder values so `prisma generate`
  // can complete. The placeholder is a syntactically valid Postgres URL
  // that will never be opened by `prisma generate` (it doesn't connect).
  console.warn(`[sync-env] root .env not found at ${ROOT_ENV}`);
  console.warn(`[sync-env] writing placeholder env for build-only contexts (CI, image builds)`);
  const placeholder = [
    "# Auto-generated by sync-env.js for build-only contexts.",
    "# Safe to ignore — prisma generate does not connect to the DB.",
    "DATABASE_URL=postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public",
  ];
  fs.writeFileSync(LOCAL_ENV, placeholder.join("\n") + "\n", "utf8");
  console.log(`[sync-env] wrote placeholder to ${path.relative(process.cwd(), LOCAL_ENV)}`);
  process.exit(0);
}

const lines = fs.readFileSync(ROOT_ENV, "utf8").split(/\r?\n/);
const out = [];
for (const key of keysToMirror) {
  const line = lines.find((l) => l.startsWith(`${key}=`));
  if (line) out.push(line);
}

if (out.length === 0) {
  console.error(`[sync-env] no DATABASE_URL found in ${ROOT_ENV}`);
  process.exit(1);
}

fs.writeFileSync(LOCAL_ENV, out.join("\n") + "\n", "utf8");
console.log(`[sync-env] wrote ${out.length} key(s) to ${path.relative(process.cwd(), LOCAL_ENV)}`);
